spring:
  application:
    name: eda

logging:
  level:
    com.pulmuone.eda: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

  jpa:

      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  