apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
bases:
  - ../base

# Set the namespace for all resources in this overlay
namespace: eda-develop

# Add environment-specific resources
resources:
  - namespace.yaml

# Generate a ConfigMap for Spring profiles environment variables.
# Kustomize will automatically append a hash to the name.
configMapGenerator:
  - name: eda-profile-env # This name is referenced in base/deployment.yaml
    literals:
      - SPRING_PROFILES_ACTIVE=develop
      - DB_HOST=host.docker.internal
