apiVersion: v1
kind: Service
metadata:
  name: eda-app-service
spec:
  # LoadBalancer 타입은 외부 IP를 할당받아 서비스를 노출합니다.
  # 로컬 환경(Minikube, Docker Desktop)에서는 각 환경에 맞는 방식으로 EXTERNAL-IP가 할당됩니다.
  type: LoadBalancer
  selector:
    app: eda-app
  ports:
    - protocol: TCP
      # 서비스 자체의 포트
      port: 8080
      # 파드의 컨테이너가 노출하는 포트
      targetPort: 8080
